SELECT SEAT_ROW, SEAT_NUMBER, IS_VIP_SEAT, (CASE WHEN (FK_CONNECTED_SEAT IS NOT NULL) THEN 'Y' ELSE 'N' END) AS IS_DOUBLE_SEAT
FROM SEATS, ROOMS, SHOWS
WHERE ID_SEAT NOT IN (
    SELECT FK_SEAT FROM TICKETS WHERE FK_SHOW IN (
        SELECT ID_SHOW FROM SHOWS JOIN ROOMS R2 on SHOWS.FK_ROOM = R2.ID_ROOM
        WHERE SHOW_DATE = TO_DATE(:show_date, 'yyyy-mm-dd')
          AND START_HOUR = :start_hour
          AND START_MINUTE = :start_minute
          AND ROOM_SIGN = :room_sign
    )
--    SELECT FK_SEAT FROM TICKETS WHERE FK_SHOW = :selected_show
)