/*WITH selected_show AS (
    SELECT ID_SHOW FROM SHOWS JOIN ROOMS R2 on SHOWS.FK_ROOM = R2.ID_ROOM
    WHERE SHOW_DATE = :show_date
    AND START_HOUR = :start_hour
    AND START_MINUTE = :start_minute
    AND ROOM_SIGN = :room_sign
)*/
SELECT SEAT_ROW, SEAT_NUMBER, IS_VIP_SEAT, FK_CONNECTED_SEAT IS NOT NULL AS IS_DOUBLE_SEAT
FROM SEATS JOIN ROOMS R on SEATS.FK_ROOM = R.ID_ROOM JOIN SHOWS S on R.ID_ROOM = S.FK_ROOM
WHERE ID_SEAT NOT IN (
--    SELECT FK_SEAT FROM TICKETS WHERE FK_SHOW = selected_show.ID_SHOW
    SELECT FK_SEAT FROM TICKETS WHERE FK_SHOW = :selected_show
)