WITH SELECTED_SHOW(THE_SHOW) AS (
    SELECT ID_SHOW AS THE_SHOW FROM SHOWS JOIN ROOMS on ROOMS.ID_ROOM = SHOWS.FK_ROOM
    WHERE
        TO_DATE(:show_date, 'yyyy-mm-dd') + NUMTODSINTERVAL(:start_hour, 'HOUR') + NUMTODSINTERVAL(:start_minutes,'MINUTE') < SHOWS.SHOW_DATE + NUMTODSINTERVAL(START_HOUR, 'HOUR') + NUMTODSINTERVAL(START_MINUTE, 'MINUTE')
        AND TO_DATE(:show_date, 'yyyy-mm-dd') + NUMTODSINTERVAL(:start_hour, 'HOUR') + NUMTODSINTERVAL(:start_minutes,'MINUTE') + NUMTODSINTERVAL(:seek_length_hours, 'HOUR') > SHOWS.SHOW_DATE + NUMTODSINTERVAL(START_HOUR, 'HOUR') + NUMTODSINTERVAL(START_MINUTE,'MINUTE')
    --WHERE ID_SHOW = :show_id
)
SELECT SEAT_ROW, SEAT_NUMBER, IS_VIP_SEAT, (CASE WHEN (FK_CONNECTED_SEAT IS NOT NULL) THEN 'Y' ELSE 'N' END) AS IS_DOUBLE_SEAT
FROM SEATS
    JOIN ROOMS ON SEATS.FK_ROOM = ROOMS.ID_ROOM
    JOIN SHOWS ON ROOMS.ID_ROOM = SHOWS.FK_ROOM
WHERE
    ID_SEAT NOT IN (SELECT FK_SEAT FROM TICKETS WHERE FK_SHOW IN (SELECT * FROM SELECTED_SHOW))
  AND ID_SHOW IN (SELECT * FROM SELECTED_SHOW);