SELECT
    FK_DUBBING_LANGUAGE AS DUBBING_LANGUAGE,
    FK_VOICE_OVER_LANGUAGE AS VOICEOVER_LANGUAGE,
    FK_SUBTITLES_LANGUAGE AS SUBTITLES_LANGUAGE,
    SUM(BASE_PRICE * (1-DISCOUNT)) AS TOTAL_INCOME,
    SUM(BASE_PRICE * DISCOUNT) AS TOTAL_DISCOUNT_VALUE
FROM MOVIES
    JOIN MOVIEVERSIONS ON MOVIES.ID_MOVIE = MOVIEVERSIONS.FK_MOVIE
    JOIN SHOWS ON MOVIEVERSIONS.ID_MOVIE_VERSION = SHOWS.FK_MOVIE_VERSION
    JOIN TICKETS ON SHOWS.ID_SHOW = TICKETS.FK_SHOW
WHERE NAME = :name
GROUP BY FK_DUBBING_LANGUAGE, FK_VOICE_OVER_LANGUAGE, FK_SUBTITLES_LANGUAGE