-- Oblicz przychód z poszczególnych wersji językowych (faktyczny przychód oraz różnica ze względu na zniżki)
-- dla różnych filmów
SELECT NAME,
       CAST(SUM(BASE_PRICE * (1 - DISCOUNT)) AS NUMBER(10, 2)) AS TOTAL_INCOME,
       CAST(SUM(BASE_PRICE * DISCOUNT) AS NUMBER(10, 2))       AS TOTAL_DISCOUNT_VALUE,
       L.LANGUAGE_NAME                                         AS ORIGINAL_LANGUAGE,
       LD.LANGUAGE_NAME                                        AS DUBBING_LANGUAGE,
       LV.LANGUAGE_NAME                                        AS VOICEOVER_LANGUAGE,
       LS.LANGUAGE_NAME                                        AS SUBTITLES_LANGUAGE
FROM MOVIES
         JOIN MOVIEVERSIONS ON ID_MOVIE = MOVIEVERSIONS.FK_MOVIE
         JOIN SHOWS ON MOVIEVERSIONS.ID_MOVIE_VERSION = SHOWS.FK_MOVIE_VERSION
         JOIN TICKETS ON SHOWS.ID_SHOW = TICKETS.FK_SHOW
         JOIN LANGUAGES L on L.ID_LANGUAGE = MOVIES.FK_LANGUAGE
         LEFT JOIN LANGUAGES LD on LD.ID_LANGUAGE = MOVIEVERSIONS.FK_DUBBING_LANGUAGE
         LEFT JOIN LANGUAGES LV on LV.ID_LANGUAGE = MOVIEVERSIONS.FK_VOICE_OVER_LANGUAGE
         LEFT JOIN LANGUAGES LS on LS.ID_LANGUAGE = MOVIEVERSIONS.FK_SUBTITLES_LANGUAGE
GROUP BY NAME, L.LANGUAGE_NAME, LD.LANGUAGE_NAME, LV.LANGUAGE_NAME, LS.LANGUAGE_NAME
ORDER BY TOTAL_DISCOUNT_VALUE DESC, TOTAL_DISCOUNT_VALUE DESC;
